app:
  image: ec2-52-88-28-198.us-west-2.compute.amazonaws.com/thingydocker:latest
  command: bash -c "sleep 5 && go-wrapper run" # sleep because the postgres container isn't ready on first start
  environment:
    TITLE: "Hooray! Scaling with docker-compose across a swarm cluster!"
    DB_USER: demo
    DB_PASS: demo
    DB_NAME: demo
    DB_SSL_MODE: disable
    INTERLOCK_DATA: '{"hostname": "foo.com", "domain":"foo.com", "port": 8080, "warm": true}'
  links:
    - "db:db"
  ports:
    - 8080
  expose:
    - 8080
db:
  image: postgres:latest
  environment:
    - "POSTGRES_USER=demo"
    - "POSTGRES_PASSWORD=demo"
  expose:
    - 5432
